name: Android Testing

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Add API key
        run: echo "$CONTENT" > app/src/main/cpp/libnative-lib.cpp
        env:
          CONTENT: ${{ secrets.LIBNATIVE_LIB_CPP_CONTENT }}

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Execute unit testing
        run: ./gradlew testDebugUnitTest
